// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcNp3CE6uxHuIetJJbMJjoThvy1n36y5k',
    appId: '1:1091018568796:web:1f77a470fca888c242e299',
    messagingSenderId: '1091018568796',
    projectId: 'lets-chat-eba12',
    authDomain: 'lets-chat-eba12.firebaseapp.com',
    storageBucket: 'lets-chat-eba12.appspot.com',
    measurementId: 'G-DK35GJJFG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcuXf9oMWuvY_hxcoYgzg-y6gm9OCVYqk',
    appId: '1:1091018568796:android:138d2bf70a10f67942e299',
    messagingSenderId: '1091018568796',
    projectId: 'lets-chat-eba12',
    storageBucket: 'lets-chat-eba12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu1OGh1FHmBlfV-4PJQ0Jwjifj7ChtjoA',
    appId: '1:1091018568796:ios:bc2a2895f48a5af342e299',
    messagingSenderId: '1091018568796',
    projectId: 'lets-chat-eba12',
    storageBucket: 'lets-chat-eba12.appspot.com',
    iosBundleId: 'com.example.letsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu1OGh1FHmBlfV-4PJQ0Jwjifj7ChtjoA',
    appId: '1:1091018568796:ios:a163ca92c2672f1842e299',
    messagingSenderId: '1091018568796',
    projectId: 'lets-chat-eba12',
    storageBucket: 'lets-chat-eba12.appspot.com',
    iosBundleId: 'com.example.letsChat.RunnerTests',
  );
}
